// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjmrubtieavcuuayhycz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqbXJ1YnRpZWF2Y3V1YXloeWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4ODA4MDMsImV4cCI6MjA2MjQ1NjgwM30.W2zffNhduvMKb-csiYAjdR-eP09MDsWzxLMOQroMUys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);